---
  - name: Copy the file from remote Server
    hosts: prod
    gather_facts: yes
    tasks:
      - name: Ping the server
        ping:
      
      - name: Copy file from Ubuntu 
        when:
         - ansible_facts ['distribution'] == "Ubuntu" 
         - ansible_facts ['hostname'] == "ubuntu"
        fetch:
          src: /tmp/tesfile.txt
          dest: /root/