---
  - name: Copy file to remote server to Ubuntu
    hosts: prod
    gather_facts: yes
    tasks:
      - name: Ping the host
        ping:

      - name: Copy file to Ubuntu
        when: ansible_distribution == 'Ubuntu'
        copy:
          src: /tmp/newfile.txt
          dest: /tmp/

        