---
  - name: Change the file permissio
    hosts: prod
    gather_facts: yes
    tasks:
      - name: Ping the server
        ping:
      
      - name: create a file with content testfile.txt on centos
        when:
         - ansible_facts ['distribution'] == "CentOS" 
        file:
          path: /tmp/testfile.txt
          state: touch
          mode: '0666'
      
